
import { useState, useEffect } from 'react';

interface IPLocationData {
  country: string;
  countryCode: string;
  phonePrefix: string;
  timezone: string;
  currency: string;
  language: string;
  isDetected: boolean;
  isLoading: boolean;
  error: string | null;
}

// Comprehensive data from LocationSettings with additions for IP detection
const countries = [
  { code: 'AD', name: 'Andorra', phone: '+376', timezone: '(GMT +01:00) Andorra', currency: 'Euro - EUR', flag: '🇦🇩', language: 'Català' },
  { code: 'AE', name: 'United Arab Emirates', phone: '+971', timezone: '(GMT +04:00) Dubai', currency: 'UAE Dirham - AED', flag: '🇦🇪', language: 'العربية' },
  { code: 'AF', name: 'Afghanistan', phone: '+93', timezone: '(GMT +04:30) Kabul', currency: 'Afghan Afghani - AFN', flag: '🇦🇫', language: 'پښتو' },
  { code: 'AG', name: 'Antigua and Barbuda', phone: '+1268', timezone: '(GMT -04:00) Antigua', currency: 'East Caribbean Dollar - XCD', flag: '🇦🇬', language: 'English' },
  { code: 'AI', name: 'Anguilla', phone: '+1264', timezone: '(GMT -04:00) Anguilla', currency: 'East Caribbean Dollar - XCD', flag: '🇦🇮', language: 'English' },
  { code: 'AL', name: 'Albania', phone: '+355', timezone: '(GMT +01:00) Tirana', currency: 'Albanian Lek - ALL', flag: '🇦🇱', language: 'Shqip' },
  { code: 'AM', name: 'Armenia', phone: '+374', timezone: '(GMT +04:00) Yerevan', currency: 'Armenian Dram - AMD', flag: '🇦🇲', language: 'Հայերեն' },
  { code: 'AO', name: 'Angola', phone: '+244', timezone: '(GMT +01:00) Luanda', currency: 'Angolan Kwanza - AOA', flag: '🇦🇴', language: 'Português' },
  { code: 'AR', name: 'Argentina', phone: '+54', timezone: '(GMT -03:00) Buenos Aires', currency: 'Argentine Peso - ARS', flag: '🇦🇷', language: 'Español' },
  { code: 'AS', name: 'American Samoa', phone: '+1684', timezone: '(GMT -11:00) Samoa', currency: 'US Dollar - USD', flag: '🇦🇸', language: 'English' },
  { code: 'AT', name: 'Austria', phone: '+43', timezone: '(GMT +01:00) Vienna', currency: 'Euro - EUR', flag: '🇦🇹', language: 'Deutsch' },
  { code: 'AU', name: 'Australia', phone: '+61', timezone: '(GMT +10:00) Sydney', currency: 'Australian Dollar - AUD', flag: '🇦🇺', language: 'English' },
  { code: 'AW', name: 'Aruba', phone: '+297', timezone: '(GMT -04:00) Aruba', currency: 'Aruban Florin - AWG', flag: '🇦🇼', language: 'Papiamento' },
  { code: 'AZ', name: 'Azerbaijan', phone: '+994', timezone: '(GMT +04:00) Baku', currency: 'Azerbaijani Manat - AZN', flag: '🇦🇿', language: 'Azərbaycan' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phone: '+387', timezone: '(GMT +01:00) Sarajevo', currency: 'Bosnia-Herzegovina Convertible Mark - BAM', flag: '🇧🇦', language: 'Bosanski' },
  { code: 'BB', name: 'Barbados', phone: '+1246', timezone: '(GMT -04:00) Barbados', currency: 'Barbadian Dollar - BBD', flag: '🇧🇧', language: 'English' },
  { code: 'BD', name: 'Bangladesh', phone: '+880', timezone: '(GMT +06:00) Dhaka', currency: 'Bangladeshi Taka - BDT', flag: '🇧🇩', language: 'বাংলা' },
  { code: 'BE', name: 'Belgium', phone: '+32', timezone: '(GMT +01:00) Brussels', currency: 'Euro - EUR', flag: '🇧🇪', language: 'Nederlands' },
  { code: 'BF', name: 'Burkina Faso', phone: '+226', timezone: '(GMT +00:00) Ouagadougou', currency: 'CFA Franc BCEAO - XOF', flag: '🇧🇫', language: 'Français' },
  { code: 'BG', name: 'Bulgaria', phone: '+359', timezone: '(GMT +02:00) Sofia', currency: 'Bulgarian Lev - BGN', flag: '🇧🇬', language: 'Български' },
  { code: 'BH', name: 'Bahrain', phone: '+973', timezone: '(GMT +03:00) Manama', currency: 'Bahraini Dinar - BHD', flag: '🇧🇭', language: 'العربية' },
  { code: 'BI', name: 'Burundi', phone: '+257', timezone: '(GMT +02:00) Bujumbura', currency: 'Burundian Franc - BIF', flag: '🇧🇮', language: 'Kirundi' },
  { code: 'BJ', name: 'Benin', phone: '+229', timezone: '(GMT +01:00) Porto-Novo', currency: 'CFA Franc BCEAO - XOF', flag: '🇧🇯', language: 'Français' },
  { code: 'BM', name: 'Bermuda', phone: '+1441', timezone: '(GMT -04:00) Bermuda', currency: 'Bermudian Dollar - BMD', flag: '🇧🇲', language: 'English' },
  { code: 'BN', name: 'Brunei', phone: '+673', timezone: '(GMT +08:00) Bandar Seri Begawan', currency: 'Brunei Dollar - BND', flag: '🇧🇳', language: 'Melayu' },
  { code: 'BO', name: 'Bolivia', phone: '+591', timezone: '(GMT -04:00) La Paz', currency: 'Bolivian Boliviano - BOB', flag: '🇧🇴', language: 'Español' },
  { code: 'BR', name: 'Brazil', phone: '+55', timezone: '(GMT -03:00) São Paulo', currency: 'Brazilian Real - BRL', flag: '🇧🇷', language: 'Português (Brasil)' },
  { code: 'BS', name: 'Bahamas', phone: '+1242', timezone: '(GMT -05:00) Nassau', currency: 'Bahamian Dollar - BSD', flag: '🇧🇸', language: 'English' },
  { code: 'BT', name: 'Bhutan', phone: '+975', timezone: '(GMT +06:00) Thimphu', currency: 'Bhutanese Ngultrum - BTN', flag: '🇧🇹', language: 'རྫོང་ཁ' },
  { code: 'BW', name: 'Botswana', phone: '+267', timezone: '(GMT +02:00) Gaborone', currency: 'Botswanan Pula - BWP', flag: '🇧🇼', language: 'English' },
  { code: 'BY', name: 'Belarus', phone: '+375', timezone: '(GMT +03:00) Minsk', currency: 'Belarusian Ruble - BYN', flag: '🇧🇾', language: 'Беларуская' },
  { code: 'BZ', name: 'Belize', phone: '+501', timezone: '(GMT -06:00) Belize', currency: 'Belize Dollar - BZD', flag: '🇧🇿', language: 'English' },
  { code: 'CA', name: 'Canada', phone: '+1', timezone: '(GMT -05:00) Toronto', currency: 'Canadian Dollar - CAD', flag: '🇨🇦', language: 'English' },
  { code: 'CD', name: 'Democratic Republic of the Congo', phone: '+243', timezone: '(GMT +01:00) Kinshasa', currency: 'Congolese Franc - CDF', flag: '🇨🇩', language: 'Français' },
  { code: 'CF', name: 'Central African Republic', phone: '+236', timezone: '(GMT +01:00) Bangui', currency: 'CFA Franc BEAC - XAF', flag: '🇨🇫', language: 'Français' },
  { code: 'CG', name: 'Republic of the Congo', phone: '+242', timezone: '(GMT +01:00) Brazzaville', currency: 'CFA Franc BEAC - XAF', flag: '🇨🇬', language: 'Français' },
  { code: 'CH', name: 'Switzerland', phone: '+41', timezone: '(GMT +01:00) Bern', currency: 'Swiss Franc - CHF', flag: '🇨🇭', language: 'Deutsch' },
  { code: 'CI', name: 'Ivory Coast', phone: '+225', timezone: '(GMT +00:00) Abidjan', currency: 'CFA Franc BCEAO - XOF', flag: '🇨🇮', language: 'Français' },
  { code: 'CK', name: 'Cook Islands', phone: '+682', timezone: '(GMT -10:00) Rarotonga', currency: 'New Zealand Dollar - NZD', flag: '🇨🇰', language: 'English' },
  { code: 'CL', name: 'Chile', phone: '+56', timezone: '(GMT -03:00) Santiago', currency: 'Chilean Peso - CLP', flag: '🇨🇱', language: 'Español' },
  { code: 'CM', name: 'Cameroon', phone: '+237', timezone: '(GMT +01:00) Yaoundé', currency: 'CFA Franc BEAC - XAF', flag: '🇨🇲', language: 'Français' },
  { code: 'CN', name: 'China', phone: '+86', timezone: '(GMT +08:00) Beijing', currency: 'Chinese Yuan - CNY', flag: '🇨🇳', language: '中文' },
  { code: 'CO', name: 'Colombia', phone: '+57', timezone: '(GMT -05:00) Bogotá', currency: 'Colombian Peso - COP', flag: '🇨🇴', language: 'Español' },
  { code: 'CR', name: 'Costa Rica', phone: '+506', timezone: '(GMT -06:00) San José', currency: 'Costa Rican Colón - CRC', flag: '🇨🇷', language: 'Español' },
  { code: 'CU', name: 'Cuba', phone: '+53', timezone: '(GMT -05:00) Havana', currency: 'Cuban Peso - CUP', flag: '🇨🇺', language: 'Español' },
  { code: 'CV', name: 'Cape Verde', phone: '+238', timezone: '(GMT -01:00) Praia', currency: 'Cape Verdean Escudo - CVE', flag: '🇨🇻', language: 'Português' },
  { code: 'CW', name: 'Curaçao', phone: '+5999', timezone: '(GMT -04:00) Willemstad', currency: 'Netherlands Antillean Guilder - ANG', flag: '🇨🇼', language: 'Papiamento' },
  { code: 'CY', name: 'Cyprus', phone: '+357', timezone: '(GMT +02:00) Nicosia', currency: 'Euro - EUR', flag: '🇨🇾', language: 'Ελληνικά' },
  { code: 'CZ', name: 'Czech Republic', phone: '+420', timezone: '(GMT +01:00) Prague', currency: 'Czech Koruna - CZK', flag: '🇨🇿', language: 'Čeština' },
  { code: 'DE', name: 'Germany', phone: '+49', timezone: '(GMT +01:00) Berlin', currency: 'Euro - EUR', flag: '🇩🇪', language: 'Deutsch' },
  { code: 'DJ', name: 'Djibouti', phone: '+253', timezone: '(GMT +03:00) Djibouti', currency: 'Djiboutian Franc - DJF', flag: '🇩🇯', language: 'Français' },
  { code: 'DK', name: 'Denmark', phone: '+45', timezone: '(GMT +01:00) Copenhagen', currency: 'Danish Krone - DKK', flag: '🇩🇰', language: 'Dansk' },
  { code: 'DM', name: 'Dominica', phone: '+1767', timezone: '(GMT -04:00) Roseau', currency: 'East Caribbean Dollar - XCD', flag: '🇩🇲', language: 'English' },
  { code: 'DO', name: 'Dominican Republic', phone: '+1809', timezone: '(GMT -04:00) Santo Domingo', currency: 'Dominican Peso - DOP', flag: '🇩🇴', language: 'Español' },
  { code: 'DZ', name: 'Algeria', phone: '+213', timezone: '(GMT +01:00) Algiers', currency: 'Algerian Dinar - DZD', flag: '🇩🇿', language: 'العربية' },
  { code: 'EC', name: 'Ecuador', phone: '+593', timezone: '(GMT -05:00) Quito', currency: 'US Dollar - USD', flag: '🇪🇨', language: 'Español' },
  { code: 'EE', name: 'Estonia', phone: '+372', timezone: '(GMT +02:00) Tallinn', currency: 'Euro - EUR', flag: '🇪🇪', language: 'Eesti' },
  { code: 'EG', name: 'Egypt', phone: '+20', timezone: '(GMT +02:00) Cairo', currency: 'Egyptian Pound - EGP', flag: '🇪🇬', language: 'العربية' },
  { code: 'ER', name: 'Eritrea', phone: '+291', timezone: '(GMT +03:00) Asmara', currency: 'Eritrean Nakfa - ERN', flag: '🇪🇷', language: 'ትግርኛ' },
  { code: 'ES', name: 'Spain', phone: '+34', timezone: '(GMT +01:00) Madrid', currency: 'Euro - EUR', flag: '🇪🇸', language: 'Español' },
  { code: 'ET', name: 'Ethiopia', phone: '+251', timezone: '(GMT +03:00) Addis Ababa', currency: 'Ethiopian Birr - ETB', flag: '🇪🇹', language: 'አማርኛ' },
  { code: 'FI', name: 'Finland', phone: '+358', timezone: '(GMT +02:00) Helsinki', currency: 'Euro - EUR', flag: '🇫🇮', language: 'Suomi' },
  { code: 'FJ', name: 'Fiji', phone: '+679', timezone: '(GMT +12:00) Suva', currency: 'Fijian Dollar - FJD', flag: '🇫🇯', language: 'English' },
  { code: 'FK', name: 'Falkland Islands', phone: '+500', timezone: '(GMT -03:00) Stanley', currency: 'Falkland Islands Pound - FKP', flag: '🇫🇰', language: 'English' },
  { code: 'FM', name: 'Micronesia', phone: '+691', timezone: '(GMT +10:00) Palikir', currency: 'US Dollar - USD', flag: '🇫🇲', language: 'English' },
  { code: 'FO', name: 'Faroe Islands', phone: '+298', timezone: '(GMT +00:00) Tórshavn', currency: 'Danish Krone - DKK', flag: '🇫🇴', language: 'Føroyskt' },
  { code: 'FR', name: 'France', phone: '+33', timezone: '(GMT +01:00) Paris', currency: 'Euro - EUR', flag: '🇫🇷', language: 'Français' },
  { code: 'GA', name: 'Gabon', phone: '+241', timezone: '(GMT +01:00) Libreville', currency: 'CFA Franc BEAC - XAF', flag: '🇬🇦', language: 'Français' },
  { code: 'GB', name: 'United Kingdom', phone: '+44', timezone: '(GMT +00:00) London', currency: 'British Pound - GBP', flag: '🇬🇧', language: 'English' },
  { code: 'GD', name: 'Grenada', phone: '+1473', timezone: '(GMT -04:00) St. George\'s', currency: 'East Caribbean Dollar - XCD', flag: '🇬🇩', language: 'English' },
  { code: 'GE', name: 'Georgia', phone: '+995', timezone: '(GMT +04:00) Tbilisi', currency: 'Georgian Lari - GEL', flag: '🇬🇪', language: 'ქართული' },
  { code: 'GF', name: 'French Guiana', phone: '+594', timezone: '(GMT -03:00) Cayenne', currency: 'Euro - EUR', flag: '🇬🇫', language: 'Français' },
  { code: 'GG', name: 'Guernsey', phone: '+44', timezone: '(GMT +00:00) St. Peter Port', currency: 'British Pound - GBP', flag: '🇬🇬', language: 'English' },
  { code: 'GH', name: 'Ghana', phone: '+233', timezone: '(GMT +00:00) Accra', currency: 'Ghanaian Cedi - GHS', flag: '🇬🇭', language: 'English' },
  { code: 'GI', name: 'Gibraltar', phone: '+350', timezone: '(GMT +01:00) Gibraltar', currency: 'Gibraltar Pound - GIP', flag: '🇬🇮', language: 'English' },
  { code: 'GL', name: 'Greenland', phone: '+299', timezone: '(GMT -03:00) Nuuk', currency: 'Danish Krone - DKK', flag: '🇬🇱', language: 'Kalaallisut' },
  { code: 'GM', name: 'Gambia', phone: '+220', timezone: '(GMT +00:00) Banjul', currency: 'Gambian Dalasi - GMD', flag: '🇬🇲', language: 'English' },
  { code: 'GN', name: 'Guinea', phone: '+224', timezone: '(GMT +00:00) Conakry', currency: 'Guinean Franc - GNF', flag: '🇬🇳', language: 'Français' },
  { code: 'GP', name: 'Guadeloupe', phone: '+590', timezone: '(GMT -04:00) Basse-Terre', currency: 'Euro - EUR', flag: '🇬🇵', language: 'Français' },
  { code: 'GQ', name: 'Equatorial Guinea', phone: '+240', timezone: '(GMT +01:00) Malabo', currency: 'CFA Franc BEAC - XAF', flag: '🇬🇶', language: 'Español' },
  { code: 'GR', name: 'Greece', phone: '+30', timezone: '(GMT +02:00) Athens', currency: 'Euro - EUR', flag: '🇬🇷', language: 'Ελληνικά' },
  { code: 'GS', name: 'South Georgia and South Sandwich Islands', phone: '+500', timezone: '(GMT -02:00) Grytviken', currency: 'British Pound - GBP', flag: '🇬🇸', language: 'English' },
  { code: 'GT', name: 'Guatemala', phone: '+502', timezone: '(GMT -06:00) Guatemala City', currency: 'Guatemalan Quetzal - GTQ', flag: '🇬🇹', language: 'Español' },
  { code: 'GU', name: 'Guam', phone: '+1671', timezone: '(GMT +10:00) Hagåtña', currency: 'US Dollar - USD', flag: '🇬🇺', language: 'English' },
  { code: 'GW', name: 'Guinea-Bissau', phone: '+245', timezone: '(GMT +00:00) Bissau', currency: 'CFA Franc BCEAO - XOF', flag: '🇬🇼', language: 'Português' },
  { code: 'GY', name: 'Guyana', phone: '+592', timezone: '(GMT -04:00) Georgetown', currency: 'Guyanaese Dollar - GYD', flag: '🇬🇾', language: 'English' },
  { code: 'HK', name: 'Hong Kong', phone: '+852', timezone: '(GMT +08:00) Hong Kong', currency: 'Hong Kong Dollar - HKD', flag: '🇭🇰', language: '中文' },
  { code: 'HN', name: 'Honduras', phone: '+504', timezone: '(GMT -06:00) Tegucigalpa', currency: 'Honduran Lempira - HNL', flag: '🇭🇳', language: 'Español' },
  { code: 'HR', name: 'Croatia', phone: '+385', timezone: '(GMT +01:00) Zagreb', currency: 'Euro - EUR', flag: '🇭🇷', language: 'Hrvatski' },
  { code: 'HT', name: 'Haiti', phone: '+509', timezone: '(GMT -05:00) Port-au-Prince', currency: 'Haitian Gourde - HTG', flag: '🇭🇹', language: 'Français' },
  { code: 'HU', name: 'Hungary', phone: '+36', timezone: '(GMT +01:00) Budapest', currency: 'Hungarian Forint - HUF', flag: '🇭🇺', language: 'Magyar' },
  { code: 'ID', name: 'Indonesia', phone: '+62', timezone: '(GMT +07:00) Jakarta', currency: 'Indonesian Rupiah - IDR', flag: '🇮🇩', language: 'Indonesia' },
  { code: 'IE', name: 'Ireland', phone: '+353', timezone: '(GMT +00:00) Dublin', currency: 'Euro - EUR', flag: '🇮🇪', language: 'English' },
  { code: 'IL', name: 'Israel', phone: '+972', timezone: '(GMT +02:00) Jerusalem', currency: 'Israeli Shekel - ILS', flag: '🇮🇱', language: 'עברית' },
  { code: 'IM', name: 'Isle of Man', phone: '+44', timezone: '(GMT +00:00) Douglas', currency: 'British Pound - GBP', flag: '🇮🇲', language: 'English' },
  { code: 'IN', name: 'India', phone: '+91', timezone: '(GMT +05:30) New Delhi', currency: 'Indian Rupee - INR', flag: '🇮🇳', language: 'English' },
  { code: 'IO', name: 'British Indian Ocean Territory', phone: '+246', timezone: '(GMT +06:00) Diego Garcia', currency: 'US Dollar - USD', flag: '🇮🇴', language: 'English' },
  { code: 'IQ', name: 'Iraq', phone: '+964', timezone: '(GMT +03:00) Baghdad', currency: 'Iraqi Dinar - IQD', flag: '🇮🇶', language: 'العربية' },
  { code: 'IR', name: 'Iran', phone: '+98', timezone: '(GMT +03:30) Tehran', currency: 'Iranian Rial - IRR', flag: '🇮🇷', language: 'فارسی' },
  { code: 'IS', name: 'Iceland', phone: '+354', timezone: '(GMT +00:00) Reykjavik', currency: 'Icelandic Króna - ISK', flag: '🇮🇸', language: 'Íslenska' },
  { code: 'IT', name: 'Italy', phone: '+39', timezone: '(GMT +01:00) Rome', currency: 'Euro - EUR', flag: '🇮🇹', language: 'Italiano' },
  { code: 'JE', name: 'Jersey', phone: '+44', timezone: '(GMT +00:00) St. Helier', currency: 'British Pound - GBP', flag: '🇯🇪', language: 'English' },
  { code: 'JM', name: 'Jamaica', phone: '+1', timezone: '(GMT -05:00) Kingston', currency: 'Jamaican Dollar - JMD', flag: '🇯🇲', language: 'English' },
  { code: 'JO', name: 'Jordan', phone: '+962', timezone: '(GMT +02:00) Amman', currency: 'Jordanian Dinar - JOD', flag: '🇯🇴', language: 'العربية' },
  { code: 'JP', name: 'Japan', phone: '+81', timezone: '(GMT +09:00) Tokyo', currency: 'Japanese Yen - JPY', flag: '🇯🇵', language: '日本語' },
  { code: 'KE', name: 'Kenya', phone: '+254', timezone: '(GMT +03:00) Nairobi', currency: 'Kenyan Shilling - KES', flag: '🇰🇪', language: 'English' },
  { code: 'KG', name: 'Kyrgyzstan', phone: '+996', timezone: '(GMT +06:00) Bishkek', currency: 'Kyrgystani Som - KGS', flag: '🇰🇬', language: 'Кыргызча' },
  { code: 'KH', name: 'Cambodia', phone: '+855', timezone: '(GMT +07:00) Phnom Penh', currency: 'Cambodian Riel - KHR', flag: '🇰🇭', language: 'ខ្មែរ' },
  { code: 'KI', name: 'Kiribati', phone: '+686', timezone: '(GMT +12:00) Tarawa', currency: 'Australian Dollar - AUD', flag: '🇰🇮', language: 'English' },
  { code: 'KM', name: 'Comoros', phone: '+269', timezone: '(GMT +03:00) Moroni', currency: 'Comorian Franc - KMF', flag: '🇰🇲', language: 'العربية' },
  { code: 'KN', name: 'Saint Kitts and Nevis', phone: '+1869', timezone: '(GMT -04:00) Basseterre', currency: 'East Caribbean Dollar - XCD', flag: '🇰🇳', language: 'English' },
  { code: 'KP', name: 'North Korea', phone: '+850', timezone: '(GMT +09:00) Pyongyang', currency: 'North Korean Won - KPW', flag: '🇰🇵', language: '한국어' },
  { code: 'KR', name: 'South Korea', phone: '+82', timezone: '(GMT +09:00) Seoul', currency: 'South Korean Won - KRW', flag: '🇰🇷', language: '한국어' },
  { code: 'KW', name: 'Kuwait', phone: '+965', timezone: '(GMT +03:00) Kuwait City', currency: 'Kuwaiti Dinar - KWD', flag: '🇰🇼', language: 'العربية' },
  { code: 'KY', name: 'Cayman Islands', phone: '+1345', timezone: '(GMT -05:00) George Town', currency: 'Cayman Islands Dollar - KYD', flag: '🇰🇾', language: 'English' },
  { code: 'KZ', name: 'Kazakhstan', phone: '+7', timezone: '(GMT +06:00) Almaty', currency: 'Kazakhstani Tenge - KZT', flag: '🇰🇿', language: 'Қазақша' },
  { code: 'LA', name: 'Laos', phone: '+856', timezone: '(GMT +07:00) Vientiane', currency: 'Laotian Kip - LAK', flag: '🇱🇦', language: 'ລາວ' },
  { code: 'LB', name: 'Lebanon', phone: '+961', timezone: '(GMT +02:00) Beirut', currency: 'Lebanese Pound - LBP', flag: '🇱🇧', language: 'العربية' },
  { code: 'LC', name: 'Saint Lucia', phone: '+1758', timezone: '(GMT -04:00) Castries', currency: 'East Caribbean Dollar - XCD', flag: '🇱🇨', language: 'English' },
  { code: 'LI', name: 'Liechtenstein', phone: '+423', timezone: '(GMT +01:00) Vaduz', currency: 'Swiss Franc - CHF', flag: '🇱🇮', language: 'Deutsch' },
  { code: 'LK', name: 'Sri Lanka', phone: '+94', timezone: '(GMT +05:30) Colombo', currency: 'Sri Lankan Rupee - LKR', flag: '🇱🇰', language: 'සිංහල' },
  { code: 'LR', name: 'Liberia', phone: '+231', timezone: '(GMT +00:00) Monrovia', currency: 'Liberian Dollar - LRD', flag: '🇱🇷', language: 'English' },
  { code: 'LS', name: 'Lesotho', phone: '+266', timezone: '(GMT +02:00) Maseru', currency: 'Lesotho Loti - LSL', flag: '🇱🇸', language: 'English' },
  { code: 'LT', name: 'Lithuania', phone: '+370', timezone: '(GMT +02:00) Vilnius', currency: 'Euro - EUR', flag: '🇱🇹', language: 'Lietuvių' },
  { code: 'LU', name: 'Luxembourg', phone: '+352', timezone: '(GMT +01:00) Luxembourg', currency: 'Euro - EUR', flag: '🇱🇺', language: 'Lëtzebuergesch' },
  { code: 'LV', name: 'Latvia', phone: '+371', timezone: '(GMT +02:00) Riga', currency: 'Euro - EUR', flag: '🇱🇻', language: 'Latviešu' },
  { code: 'LY', name: 'Libya', phone: '+218', timezone: '(GMT +02:00) Tripoli', currency: 'Libyan Dinar - LYD', flag: '🇱🇾', language: 'العربية' },
  { code: 'MA', name: 'Morocco', phone: '+212', timezone: '(GMT +00:00) Casablanca', currency: 'Moroccan Dirham - MAD', flag: '🇲🇦', language: 'العربية' },
  { code: 'MC', name: 'Monaco', phone: '+377', timezone: '(GMT +01:00) Monaco', currency: 'Euro - EUR', flag: '🇲🇨', language: 'Français' },
  { code: 'MD', name: 'Moldova', phone: '+373', timezone: '(GMT +02:00) Chișinău', currency: 'Moldovan Leu - MDL', flag: '🇲🇩', language: 'Română' },
  { code: 'ME', name: 'Montenegro', phone: '+382', timezone: '(GMT +01:00) Podgorica', currency: 'Euro - EUR', flag: '🇲🇪', language: 'Crnogorski' },
  { code: 'MF', name: 'Saint Martin', phone: '+590', timezone: '(GMT -04:00) Marigot', currency: 'Euro - EUR', flag: '🇲🇫', language: 'Français' },
  { code: 'MG', name: 'Madagascar', phone: '+261', timezone: '(GMT +03:00) Antananarivo', currency: 'Malagasy Ariary - MGA', flag: '🇲🇬', language: 'Malagasy' },
  { code: 'MH', name: 'Marshall Islands', phone: '+692', timezone: '(GMT +12:00) Majuro', currency: 'US Dollar - USD', flag: '🇲🇭', language: 'English' },
  { code: 'MK', name: 'North Macedonia', phone: '+389', timezone: '(GMT +01:00) Skopje', currency: 'Macedonian Denar - MKD', flag: '🇲🇰', language: 'Македонски' },
  { code: 'ML', name: 'Mali', phone: '+223', timezone: '(GMT +00:00) Bamako', currency: 'CFA Franc BCEAO - XOF', flag: '🇲🇱', language: 'Français' },
  { code: 'MM', name: 'Myanmar', phone: '+95', timezone: '(GMT +06:30) Naypyidaw', currency: 'Myanmar Kyat - MMK', flag: '🇲🇲', language: 'မြန်မာ' },
  { code: 'MN', name: 'Mongolia', phone: '+976', timezone: '(GMT +08:00) Ulaanbaatar', currency: 'Mongolian Tugrik - MNT', flag: '🇲🇳', language: 'Монгол' },
  { code: 'MO', name: 'Macau', phone: '+853', timezone: '(GMT +08:00) Macau', currency: 'Macanese Pataca - MOP', flag: '🇲🇴', language: '中文' },
  { code: 'MP', name: 'Northern Mariana Islands', phone: '+1670', timezone: '(GMT +10:00) Saipan', currency: 'US Dollar - USD', flag: '🇲🇵', language: 'English' },
  { code: 'MQ', name: 'Martinique', phone: '+596', timezone: '(GMT -04:00) Fort-de-France', currency: 'Euro - EUR', flag: '🇲🇶', language: 'Français' },
  { code: 'MR', name: 'Mauritania', phone: '+222', timezone: '(GMT +00:00) Nouakchott', currency: 'Mauritanian Ouguiya - MRU', flag: '🇲🇷', language: 'العربية' },
  { code: 'MS', name: 'Montserrat', phone: '+1664', timezone: '(GMT -04:00) Plymouth', currency: 'East Caribbean Dollar - XCD', flag: '🇲🇸', language: 'English' },
  { code: 'MT', name: 'Malta', phone: '+356', timezone: '(GMT +01:00) Valletta', currency: 'Euro - EUR', flag: '🇲🇹', language: 'Malti' },
  { code: 'MU', name: 'Mauritius', phone: '+230', timezone: '(GMT +04:00) Port Louis', currency: 'Mauritian Rupee - MUR', flag: '🇲🇺', language: 'English' },
  { code: 'MV', name: 'Maldives', phone: '+960', timezone: '(GMT +05:00) Malé', currency: 'Maldivian Rufiyaa - MVR', flag: '🇲🇻', language: 'Dhivehi' },
  { code: 'MW', name: 'Malawi', phone: '+265', timezone: '(GMT +02:00) Lilongwe', currency: 'Malawian Kwacha - MWK', flag: '🇲🇼', language: 'English' },
  { code: 'MX', name: 'Mexico', phone: '+52', timezone: '(GMT -06:00) Mexico City', currency: 'Mexican Peso - MXN', flag: '🇲🇽', language: 'Español' },
  { code: 'MY', name: 'Malaysia', phone: '+60', timezone: '(GMT +08:00) Kuala Lumpur', currency: 'Malaysian Ringgit - MYR', flag: '🇲🇾', language: 'English' },
  { code: 'MZ', name: 'Mozambique', phone: '+258', timezone: '(GMT +02:00) Maputo', currency: 'Mozambican Metical - MZN', flag: '🇲🇿', language: 'Português' },
  { code: 'NA', name: 'Namibia', phone: '+264', timezone: '(GMT +02:00) Windhoek', currency: 'Namibian Dollar - NAD', flag: '🇳🇦', language: 'English' },
  { code: 'NC', name: 'New Caledonia', phone: '+687', timezone: '(GMT +11:00) Nouméa', currency: 'CFP Franc - XPF', flag: '🇳🇨', language: 'Français' },
  { code: 'NE', name: 'Niger', phone: '+227', timezone: '(GMT +01:00) Niamey', currency: 'CFA Franc BCEAO - XOF', flag: '🇳🇪', language: 'Français' },
  { code: 'NF', name: 'Norfolk Island', phone: '+672', timezone: '(GMT +11:00) Kingston', currency: 'Australian Dollar - AUD', flag: '🇳🇫', language: 'English' },
  { code: 'NG', name: 'Nigeria', phone: '+234', timezone: '(GMT +01:00) Lagos', currency: 'Nigerian Naira - NGN', flag: '🇳🇬', language: 'English' },
  { code: 'NI', name: 'Nicaragua', phone: '+505', timezone: '(GMT -06:00) Managua', currency: 'Nicaraguan Córdoba - NIO', flag: '🇳🇮', language: 'Español' },
  { code: 'NL', name: 'Netherlands', phone: '+31', timezone: '(GMT +01:00) Amsterdam', currency: 'Euro - EUR', flag: '🇳🇱', language: 'Nederlands' },
  { code: 'NO', name: 'Norway', phone: '+47', timezone: '(GMT +01:00) Oslo', currency: 'Norwegian Krone - NOK', flag: '🇳🇴', language: 'Norsk' },
  { code: 'NP', name: 'Nepal', phone: '+977', timezone: '(GMT +05:45) Kathmandu', currency: 'Nepalese Rupee - NPR', flag: '🇳🇵', language: 'नेपाली' },
  { code: 'NR', name: 'Nauru', phone: '+674', timezone: '(GMT +12:00) Yaren', currency: 'Australian Dollar - AUD', flag: '🇳🇷', language: 'English' },
  { code: 'NU', name: 'Niue', phone: '+683', timezone: '(GMT -11:00) Alofi', currency: 'New Zealand Dollar - NZD', flag: '🇳🇺', language: 'English' },
  { code: 'NZ', name: 'New Zealand', phone: '+64', timezone: '(GMT +12:00) Auckland', currency: 'New Zealand Dollar - NZD', flag: '🇳🇿', language: 'English' },
  { code: 'OM', name: 'Oman', phone: '+968', timezone: '(GMT +04:00) Muscat', currency: 'Omani Rial - OMR', flag: '🇴🇲', language: 'العربية' },
  { code: 'PA', name: 'Panama', phone: '+507', timezone: '(GMT -05:00) Panama City', currency: 'Panamanian Balboa - PAB', flag: '🇵🇦', language: 'Español' },
  { code: 'PE', name: 'Peru', phone: '+51', timezone: '(GMT -05:00) Lima', currency: 'Peruvian Sol - PEN', flag: '🇵🇪', language: 'Español' },
  { code: 'PF', name: 'French Polynesia', phone: '+689', timezone: '(GMT -10:00) Papeete', currency: 'CFP Franc - XPF', flag: '🇵🇫', language: 'Français' },
  { code: 'PG', name: 'Papua New Guinea', phone: '+675', timezone: '(GMT +10:00) Port Moresby', currency: 'Papua New Guinean Kina - PGK', flag: '🇵🇬', language: 'English' },
  { code: 'PH', name: 'Philippines', phone: '+63', timezone: '(GMT +08:00) Manila', currency: 'Philippine Peso - PHP', flag: '🇵🇭', language: 'English' },
  { code: 'PK', name: 'Pakistan', phone: '+92', timezone: '(GMT +05:00) Karachi', currency: 'Pakistani Rupee - PKR', flag: '🇵🇰', language: 'اردو' },
  { code: 'PL', name: 'Poland', phone: '+48', timezone: '(GMT +01:00) Warsaw', currency: 'Polish Złoty - PLN', flag: '🇵🇱', language: 'Polski' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', phone: '+508', timezone: '(GMT -03:00) Saint-Pierre', currency: 'Euro - EUR', flag: '🇵🇲', language: 'Français' },
  { code: 'PN', name: 'Pitcairn Islands', phone: '+64', timezone: '(GMT -08:00) Adamstown', currency: 'New Zealand Dollar - NZD', flag: '🇵🇳', language: 'English' },
  { code: 'PR', name: 'Puerto Rico', phone: '+1787', timezone: '(GMT -04:00) San Juan', currency: 'US Dollar - USD', flag: '🇵🇷', language: 'Español' },
  { code: 'PS', name: 'Palestine', phone: '+970', timezone: '(GMT +02:00) Gaza', currency: 'Israeli Shekel - ILS', flag: '🇵🇸', language: 'العربية' },
  { code: 'PT', name: 'Portugal', phone: '+351', timezone: '(GMT +00:00) Lisbon', currency: 'Euro - EUR', flag: '🇵🇹', language: 'Português' },
  { code: 'PW', name: 'Palau', phone: '+680', timezone: '(GMT +09:00) Ngerulmud', currency: 'US Dollar - USD', flag: '🇵🇼', language: 'English' },
  { code: 'PY', name: 'Paraguay', phone: '+595', timezone: '(GMT -03:00) Asunción', currency: 'Paraguayan Guarani - PYG', flag: '🇵🇾', language: 'Español' },
  { code: 'QA', name: 'Qatar', phone: '+974', timezone: '(GMT +03:00) Doha', currency: 'Qatari Riyal - QAR', flag: '🇶🇦', language: 'العربية' },
  { code: 'RE', name: 'Réunion', phone: '+262', timezone: '(GMT +04:00) Saint-Denis', currency: 'Euro - EUR', flag: '🇷🇪', language: 'Français' },
  { code: 'RO', name: 'Romania', phone: '+40', timezone: '(GMT +02:00) Bucharest', currency: 'Romanian Leu - RON', flag: '🇷🇴', language: 'Română' },
  { code: 'RS', name: 'Serbia', phone: '+381', timezone: '(GMT +01:00) Belgrade', currency: 'Serbian Dinar - RSD', flag: '🇷🇸', language: 'Српски' },
  { code: 'RU', name: 'Russia', phone: '+7', timezone: '(GMT +03:00) Moscow', currency: 'Russian Ruble - RUB', flag: '🇷🇺', language: 'Русский' },
  { code: 'RW', name: 'Rwanda', phone: '+250', timezone: '(GMT +02:00) Kigali', currency: 'Rwandan Franc - RWF', flag: '🇷🇼', language: 'Kinyarwanda' },
  { code: 'SA', name: 'Saudi Arabia', phone: '+966', timezone: '(GMT +03:00) Riyadh', currency: 'Saudi Riyal - SAR', flag: '🇸🇦', language: 'العربية' },
  { code: 'SB', name: 'Solomon Islands', phone: '+677', timezone: '(GMT +11:00) Honiara', currency: 'Solomon Islands Dollar - SBD', flag: '🇸🇧', language: 'English' },
  { code: 'SC', name: 'Seychelles', phone: '+248', timezone: '(GMT +04:00) Victoria', currency: 'Seychellois Rupee - SCR', flag: '🇸🇨', language: 'English' },
  { code: 'SD', name: 'Sudan', phone: '+249', timezone: '(GMT +02:00) Khartoum', currency: 'Sudanese Pound - SDG', flag: '🇸🇩', language: 'العربية' },
  { code: 'SE', name: 'Sweden', phone: '+46', timezone: '(GMT +01:00) Stockholm', currency: 'Swedish Krona - SEK', flag: '🇸🇪', language: 'Svenska' },
  { code: 'SG', name: 'Singapore', phone: '+65', timezone: '(GMT +08:00) Singapore', currency: 'Singapore Dollar - SGD', flag: '🇸🇬', language: 'English' },
  { code: 'SH', name: 'Saint Helena', phone: '+290', timezone: '(GMT +00:00) Jamestown', currency: 'Saint Helena Pound - SHP', flag: '🇸🇭', language: 'English' },
  { code: 'SI', name: 'Slovenia', phone: '+386', timezone: '(GMT +01:00) Ljubljana', currency: 'Euro - EUR', flag: '🇸🇮', language: 'Slovenščina' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', phone: '+47', timezone: '(GMT +01:00) Longyearbyen', currency: 'Norwegian Krone - NOK', flag: '🇸🇯', language: 'Norsk' },
  { code: 'SK', name: 'Slovakia', phone: '+421', timezone: '(GMT +01:00) Bratislava', currency: 'Euro - EUR', flag: '🇸🇰', language: 'Slovenčina' },
  { code: 'SL', name: 'Sierra Leone', phone: '+232', timezone: '(GMT +00:00) Freetown', currency: 'Sierra Leonean Leone - SLE', flag: '🇸🇱', language: 'English' },
  { code: 'SM', name: 'San Marino', phone: '+378', timezone: '(GMT +01:00) San Marino', currency: 'Euro - EUR', flag: '🇸🇲', language: 'Italiano' },
  { code: 'SN', name: 'Senegal', phone: '+221', timezone: '(GMT +00:00) Dakar', currency: 'CFA Franc BCEAO - XOF', flag: '🇸🇳', language: 'Français' },
  { code: 'SO', name: 'Somalia', phone: '+252', timezone: '(GMT +03:00) Mogadishu', currency: 'Somali Shilling - SOS', flag: '🇸🇴', language: 'Soomaali' },
  { code: 'SR', name: 'Suriname', phone: '+597', timezone: '(GMT -03:00) Paramaribo', currency: 'Surinamese Dollar - SRD', flag: '🇸🇷', language: 'Nederlands' },
  { code: 'SS', name: 'South Sudan', phone: '+211', timezone: '(GMT +03:00) Juba', currency: 'South Sudanese Pound - SSP', flag: '🇸🇸', language: 'English' },
  { code: 'ST', name: 'São Tomé and Príncipe', phone: '+239', timezone: '(GMT +00:00) São Tomé', currency: 'São Tomé and Príncipe Dobra - STN', flag: '🇸🇹', language: 'Português' },
  { code: 'SV', name: 'El Salvador', phone: '+503', timezone: '(GMT -06:00) San Salvador', currency: 'US Dollar - USD', flag: '🇸🇻', language: 'Español' },
  { code: 'SX', name: 'Sint Maarten', phone: '+1721', timezone: '(GMT -04:00) Philipsburg', currency: 'Netherlands Antillean Guilder - ANG', flag: '🇸🇽', language: 'Nederlands' },
  { code: 'SY', name: 'Syria', phone: '+963', timezone: '(GMT +02:00) Damascus', currency: 'Syrian Pound - SYP', flag: '🇸🇾', language: 'العربية' },
  { code: 'SZ', name: 'Eswatini', phone: '+268', timezone: '(GMT +02:00) Mbabane', currency: 'Swazi Lilangeni - SZL', flag: '🇸🇿', language: 'English' },
  { code: 'TC', name: 'Turks and Caicos Islands', phone: '+1649', timezone: '(GMT -05:00) Cockburn Town', currency: 'US Dollar - USD', flag: '🇹🇨', language: 'English' },
  { code: 'TD', name: 'Chad', phone: '+235', timezone: '(GMT +01:00) N\'Djamena', currency: 'CFA Franc BEAC - XAF', flag: '🇹🇩', language: 'Français' },
  { code: 'TF', name: 'French Southern Territories', phone: '+262', timezone: '(GMT +05:00) Port-aux-Français', currency: 'Euro - EUR', flag: '🇹🇫', language: 'Français' },
  { code: 'TG', name: 'Togo', phone: '+228', timezone: '(GMT +00:00) Lomé', currency: 'CFA Franc BCEAO - XOF', flag: '🇹🇬', language: 'Français' },
  { code: 'TH', name: 'Thailand', phone: '+66', timezone: '(GMT +07:00) Bangkok', currency: 'Thai Baht - THB', flag: '🇹🇭', language: 'ไทย' },
  { code: 'TJ', name: 'Tajikistan', phone: '+992', timezone: '(GMT +05:00) Dushanbe', currency: 'Tajikistani Somoni - TJS', flag: '🇹🇯', language: 'Тоҷикӣ' },
  { code: 'TK', name: 'Tokelau', phone: '+690', timezone: '(GMT +13:00) Fakaofo', currency: 'New Zealand Dollar - NZD', flag: '🇹🇰', language: 'English' },
  { code: 'TL', name: 'Timor-Leste', phone: '+670', timezone: '(GMT +09:00) Dili', currency: 'US Dollar - USD', flag: '🇹🇱', language: 'Português' },
  { code: 'TM', name: 'Turkmenistan', phone: '+993', timezone: '(GMT +05:00) Ashgabat', currency: 'Turkmenistani Manat - TMT', flag: '🇹🇲', language: 'Türkmençe' },
  { code: 'TN', name: 'Tunisia', phone: '+216', timezone: '(GMT +01:00) Tunis', currency: 'Tunisian Dinar - TND', flag: '🇹🇳', language: 'العربية' },
  { code: 'TO', name: 'Tonga', phone: '+676', timezone: '(GMT +13:00) Nuku\'alofa', currency: 'Tongan Paʻanga - TOP', flag: '🇹🇴', language: 'English' },
  { code: 'TR', name: 'Turkey', phone: '+90', timezone: '(GMT +03:00) Istanbul', currency: 'Turkish Lira - TRY', flag: '🇹🇷', language: 'Türkçe' },
  { code: 'TT', name: 'Trinidad and Tobago', phone: '+1868', timezone: '(GMT -04:00) Port of Spain', currency: 'Trinidad and Tobago Dollar - TTD', flag: '🇹🇹', language: 'English' },
  { code: 'TV', name: 'Tuvalu', phone: '+688', timezone: '(GMT +12:00) Funafuti', currency: 'Australian Dollar - AUD', flag: '🇹🇻', language: 'English' },
  { code: 'TW', name: 'Taiwan', phone: '+886', timezone: '(GMT +08:00) Taipei', currency: 'New Taiwan Dollar - TWD', flag: '🇹🇼', language: '中文' },
  { code: 'TZ', name: 'Tanzania', phone: '+255', timezone: '(GMT +03:00) Dodoma', currency: 'Tanzanian Shilling - TZS', flag: '🇹🇿', language: 'Kiswahili' },
  { code: 'UA', name: 'Ukraine', phone: '+380', timezone: '(GMT +02:00) Kyiv', currency: 'Ukrainian Hryvnia - UAH', flag: '🇺🇦', language: 'Українська' },
  { code: 'UG', name: 'Uganda', phone: '+256', timezone: '(GMT +03:00) Kampala', currency: 'Ugandan Shilling - UGX', flag: '🇺🇬', language: 'English' },
  { code: 'UM', name: 'United States Minor Outlying Islands', phone: '+1', timezone: '(GMT -12:00) Baker Island', currency: 'US Dollar - USD', flag: '🇺🇲', language: 'English' },
  { code: 'US', name: 'United States', phone: '+1', timezone: '(GMT -05:00) New York', currency: 'US Dollar - USD', flag: '🇺🇸', language: 'English' },
  { code: 'UY', name: 'Uruguay', phone: '+598', timezone: '(GMT -03:00) Montevideo', currency: 'Uruguayan Peso - UYU', flag: '🇺🇾', language: 'Español' },
  { code: 'UZ', name: 'Uzbekistan', phone: '+998', timezone: '(GMT +05:00) Tashkent', currency: 'Uzbekistani Som - UZS', flag: '🇺🇿', language: 'Oʻzbekcha' },
  { code: 'VA', name: 'Vatican City', phone: '+39', timezone: '(GMT +01:00) Vatican City', currency: 'Euro - EUR', flag: '🇻🇦', language: 'Italiano' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', phone: '+1784', timezone: '(GMT -04:00) Kingstown', currency: 'East Caribbean Dollar - XCD', flag: '🇻🇨', language: 'English' },
  { code: 'VE', name: 'Venezuela', phone: '+58', timezone: '(GMT -04:00) Caracas', currency: 'Venezuelan Bolívar - VES', flag: '🇻🇪', language: 'Español' },
  { code: 'VG', name: 'British Virgin Islands', phone: '+1284', timezone: '(GMT -04:00) Road Town', currency: 'US Dollar - USD', flag: '🇻🇬', language: 'English' },
  { code: 'VI', name: 'United States Virgin Islands', phone: '+1340', timezone: '(GMT -04:00) Charlotte Amalie', currency: 'US Dollar - USD', flag: '🇻🇮', language: 'English' },
  { code: 'VN', name: 'Vietnam', phone: '+84', timezone: '(GMT +07:00) Ho Chi Minh City', currency: 'Vietnamese Dong - VND', flag: '🇻🇳', language: 'Tiếng Việt' },
  { code: 'VU', name: 'Vanuatu', phone: '+678', timezone: '(GMT +11:00) Port Vila', currency: 'Vanuatu Vatu - VUV', flag: '🇻🇺', language: 'English' },
  { code: 'WF', name: 'Wallis and Futuna', phone: '+681', timezone: '(GMT +12:00) Mata-Utu', currency: 'CFP Franc - XPF', flag: '🇼🇫', language: 'Français' },
  { code: 'WS', name: 'Samoa', phone: '+685', timezone: '(GMT +13:00) Apia', currency: 'Samoan Tālā - WST', flag: '🇼🇸', language: 'English' },
  { code: 'YE', name: 'Yemen', phone: '+967', timezone: '(GMT +03:00) Sana\'a', currency: 'Yemeni Rial - YER', flag: '🇾🇪', language: 'العربية' },
  { code: 'YT', name: 'Mayotte', phone: '+262', timezone: '(GMT +03:00) Mamoudzou', currency: 'Euro - EUR', flag: '🇾🇹', language: 'Français' },
  { code: 'ZA', name: 'South Africa', phone: '+27', timezone: '(GMT +02:00) Johannesburg', currency: 'South African Rand - ZAR', flag: '🇿🇦', language: 'English' },
  { code: 'ZM', name: 'Zambia', phone: '+260', timezone: '(GMT +02:00) Lusaka', currency: 'Zambian Kwacha - ZMW', flag: '🇿🇲', language: 'English' },
  { code: 'ZW', name: 'Zimbabwe', phone: '+263', timezone: '(GMT +02:00) Harare', currency: 'Zimbabwean Dollar - ZWL', flag: '🇿🇼', language: 'English' },
];

// Comprehensive timezone list
const timezones = [
  '(GMT -12:00) Baker Island',
  '(GMT -11:00) American Samoa',
  '(GMT -11:00) Midway Island',
  '(GMT -11:00) Niue',
  '(GMT -11:00) Samoa',
  '(GMT -10:00) Cook Islands',
  '(GMT -10:00) French Polynesia',
  '(GMT -10:00) Hawaii',
  '(GMT -09:30) Marquesas Islands',
  '(GMT -09:00) Alaska',
  '(GMT -08:00) Pacific Time (US & Canada)',
  '(GMT -07:00) Mountain Time (US & Canada)',
  '(GMT -06:00) Central Time (US & Canada)',
  '(GMT -06:00) Mexico City',
  '(GMT -05:00) Eastern Time (US & Canada)',
  '(GMT -05:00) New York',
  '(GMT -05:00) Toronto',
  '(GMT -05:00) Bogotá',
  '(GMT -05:00) Lima',
  '(GMT -04:30) Caracas',
  '(GMT -04:00) Atlantic Time (Canada)',
  '(GMT -04:00) Santiago',
  '(GMT -03:30) Newfoundland',
  '(GMT -03:00) Brazil',
  '(GMT -03:00) São Paulo',
  '(GMT -03:00) Buenos Aires',
  '(GMT -02:00) Mid-Atlantic',
  '(GMT -01:00) Azores',
  '(GMT +00:00) Greenwich Mean Time',
  '(GMT +00:00) London',
  '(GMT +00:00) Casablanca',
  '(GMT +01:00) Central European Time',
  '(GMT +01:00) Berlin',
  '(GMT +01:00) Paris',
  '(GMT +01:00) Rome',
  '(GMT +01:00) Madrid',
  '(GMT +01:00) Amsterdam',
  '(GMT +01:00) Lagos',
  '(GMT +02:00) Eastern European Time',
  '(GMT +02:00) Cairo',
  '(GMT +02:00) Johannesburg',
  '(GMT +02:00) Jerusalem',
  '(GMT +03:00) Moscow',
  '(GMT +03:00) Istanbul',
  '(GMT +03:00) Riyadh',
  '(GMT +03:00) Nairobi',
  '(GMT +03:30) Tehran',
  '(GMT +04:00) Dubai',
  '(GMT +04:00) Baku',
  '(GMT +04:30) Kabul',
  '(GMT +05:00) Pakistan',
  '(GMT +05:30) India',
  '(GMT +05:30) New Delhi',
  '(GMT +05:45) Nepal',
  '(GMT +06:00) Bangladesh',
  '(GMT +06:30) Myanmar',
  '(GMT +07:00) Bangkok',
  '(GMT +07:00) Jakarta',
  '(GMT +07:00) Ho Chi Minh City',
  '(GMT +08:00) China Standard Time',
  '(GMT +08:00) Beijing',
  '(GMT +08:00) Singapore',
  '(GMT +08:00) Kuala Lumpur',
  '(GMT +08:00) Manila',
  '(GMT +08:00) Perth',
  '(GMT +08:45) Eucla',
  '(GMT +09:00) Japan Standard Time',
  '(GMT +09:00) Tokyo',
  '(GMT +09:00) Seoul',
  '(GMT +09:30) Adelaide',
  '(GMT +10:00) Australian Eastern Time',
  '(GMT +10:00) Sydney',
  '(GMT +10:30) Lord Howe Island',
  '(GMT +11:00) Solomon Islands',
  '(GMT +11:30) Norfolk Island',
  '(GMT +12:00) New Zealand',
  '(GMT +12:45) Chatham Islands',
  '(GMT +13:00) Tonga',
  '(GMT +14:00) Line Islands',
];

// Comprehensive currencies list
const currencies = [
  'Afghan Afghani - AFN',
  'Albanian Lek - ALL',
  'Algerian Dinar - DZD',
  'Angolan Kwanza - AOA',
  'Argentine Peso - ARS',
  'Armenian Dram - AMD',
  'Aruban Florin - AWG',
  'Australian Dollar - AUD',
  'Azerbaijani Manat - AZN',
  'Bahamian Dollar - BSD',
  'Bahraini Dinar - BHD',
  'Bangladeshi Taka - BDT',
  'Barbadian Dollar - BBD',
  'Belarusian Ruble - BYN',
  'Belize Dollar - BZD',
  'Bermudian Dollar - BMD',
  'Bhutanese Ngultrum - BTN',
  'Bolivian Boliviano - BOB',
  'Bosnia-Herzegovina Convertible Mark - BAM',
  'Botswanan Pula - BWP',
  'Brazilian Real - BRL',
  'British Pound - GBP',
  'Brunei Dollar - BND',
  'Bulgarian Lev - BGN',
  'Burundian Franc - BIF',
  'Cambodian Riel - KHR',
  'Canadian Dollar - CAD',
  'Cape Verdean Escudo - CVE',
  'Cayman Islands Dollar - KYD',
  'CFA Franc BCEAO - XOF',
  'CFA Franc BEAC - XAF',
  'CFP Franc - XPF',
  'Chilean Peso - CLP',
  'Chinese Yuan - CNY',
  'Colombian Peso - COP',
  'Comorian Franc - KMF',
  'Congolese Franc - CDF',
  'Costa Rican Colón - CRC',
  'Croatian Kuna - HRK',
  'Cuban Peso - CUP',
  'Czech Koruna - CZK',
  'Danish Krone - DKK',
  'Djiboutian Franc - DJF',
  'Dominican Peso - DOP',
  'East Caribbean Dollar - XCD',
  'Egyptian Pound - EGP',
  'Eritrean Nakfa - ERN',
  'Estonian Kroon - EEK',
  'Ethiopian Birr - ETB',
  'Euro - EUR',
  'Falkland Islands Pound - FKP',
  'Fijian Dollar - FJD',
  'Gambian Dalasi - GMD',
  'Georgian Lari - GEL',
  'Ghanaian Cedi - GHS',
  'Gibraltar Pound - GIP',
  'Guatemalan Quetzal - GTQ',
  'Guinean Franc - GNF',
  'Guyanaese Dollar - GYD',
  'Haitian Gourde - HTG',
  'Honduran Lempira - HNL',
  'Hong Kong Dollar - HKD',
  'Hungarian Forint - HUF',
  'Icelandic Króna - ISK',
  'Indian Rupee - INR',
  'Indonesian Rupiah - IDR',
  'Iranian Rial - IRR',
  'Iraqi Dinar - IQD',
  'Israeli Shekel - ILS',
  'Jamaican Dollar - JMD',
  'Japanese Yen - JPY',
  'Jordanian Dinar - JOD',
  'Kazakhstani Tenge - KZT',
  'Kenyan Shilling - KES',
  'Kuwaiti Dinar - KWD',
  'Kyrgystani Som - KGS',
  'Laotian Kip - LAK',
  'Latvian Lats - LVL',
  'Lebanese Pound - LBP',
  'Lesotho Loti - LSL',
  'Liberian Dollar - LRD',
  'Libyan Dinar - LYD',
  'Lithuanian Litas - LTL',
  'Macanese Pataca - MOP',
  'Macedonian Denar - MKD',
  'Malagasy Ariary - MGA',
  'Malawian Kwacha - MWK',
  'Malaysian Ringgit - MYR',
  'Maldivian Rufiyaa - MVR',
  'Mauritanian Ouguiya - MRU',
  'Mauritian Rupee - MUR',
  'Mexican Peso - MXN',
  'Moldovan Leu - MDL',
  'Mongolian Tugrik - MNT',
  'Moroccan Dirham - MAD',
  'Mozambican Metical - MZN',
  'Myanmar Kyat - MMK',
  'Namibian Dollar - NAD',
  'Nepalese Rupee - NPR',
  'Netherlands Antillean Guilder - ANG',
  'New Taiwan Dollar - TWD',
  'New Zealand Dollar - NZD',
  'Nicaraguan Córdoba - NIO',
  'Nigerian Naira - NGN',
  'North Korean Won - KPW',
  'Norwegian Krone - NOK',
  'Omani Rial - OMR',
  'Pakistani Rupee - PKR',
  'Panamanian Balboa - PAB',
  'Papua New Guinean Kina - PGK',
  'Paraguayan Guarani - PYG',
  'Peruvian Sol - PEN',
  'Philippine Peso - PHP',
  'Polish Złoty - PLN',
  'Qatari Riyal - QAR',
  'Romanian Leu - RON',
  'Russian Ruble - RUB',
  'Rwandan Franc - RWF',
  'Saint Helena Pound - SHP',
  'Samoan Tālā - WST',
  'São Tomé and Príncipe Dobra - STN',
  'Saudi Riyal - SAR',
  'Serbian Dinar - RSD',
  'Seychellois Rupee - SCR',
  'Sierra Leonean Leone - SLE',
  'Singapore Dollar - SGD',
  'Slovak Koruna - SKK',
  'Solomon Islands Dollar - SBD',
  'Somali Shilling - SOS',
  'South African Rand - ZAR',
  'South Korean Won - KRW',
  'Sri Lankan Rupee - LKR',
  'Sudanese Pound - SDG',
  'Surinamese Dollar - SRD',
  'Swazi Lilangeni - SZL',
  'Swedish Krona - SEK',
  'Swiss Franc - CHF',
  'Syrian Pound - SYP',
  'Tajikistani Somoni - TJS',
  'Tanzanian Shilling - TZS',
  'Thai Baht - THB',
  'Tongan Paʻanga - TOP',
  'Trinidad and Tobago Dollar - TTD',
  'Tunisian Dinar - TND',
  'Turkish Lira - TRY',
  'Turkmenistani Manat - TMT',
  'Ugandan Shilling - UGX',
  'Ukrainian Hryvnia - UAH',
  'UAE Dirham - AED',
  'US Dollar - USD',
  'Uruguayan Peso - UYU',
  'Uzbekistani Som - UZS',
  'Vanuatu Vatu - VUV',
  'Venezuelan Bolívar - VES',
  'Vietnamese Dong - VND',
  'Yemeni Rial - YER',
  'Zambian Kwacha - ZMW',
  'Zimbabwean Dollar - ZWL',
];

// Languages list with flags
const languages = [
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'bg', name: 'Български', flag: '🇧🇬' },
  { code: 'cs', name: 'Čeština', flag: '🇨🇿' },
  { code: 'da', name: 'Dansk', flag: '🇩🇰' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'el', name: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fi', name: 'Suomi', flag: '🇫🇮' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'he', name: 'עברית', flag: '🇮🇱' },
  { code: 'hr', name: 'Hrvatski', flag: '🇭🇷' },
  { code: 'hu', name: 'Magyar', flag: '🇭🇺' },
  { code: 'id', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'lt', name: 'Lietuvių', flag: '🇱🇹' },
  { code: 'nb', name: 'Norsk Bokmål', flag: '🇳🇴' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
  { code: 'pt', name: 'Português (Brasil)', flag: '🇧🇷' },
  { code: 'ro', name: 'Română', flag: '🇷🇴' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'sl', name: 'Slovenščina', flag: '🇸🇮' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
  { code: 'th', name: 'ไทย', flag: '🇹🇭' },
  { code: 'uk', name: 'Українська', flag: '🇺🇦' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
];

export const useIPLocationDetection = (): IPLocationData => {
  const [locationData, setLocationData] = useState<IPLocationData>({
    country: '',
    countryCode: '',
    phonePrefix: '',
    timezone: '',
    currency: '',
    language: 'English',
    isDetected: false,
    isLoading: true,
    error: null,
  });

  useEffect(() => {
    const detectLocation = async () => {
      try {
        setLocationData(prev => ({ ...prev, isLoading: true, error: null }));

        // Use multiple IP geolocation services as fallbacks
        const services = [
          'https://ipapi.co/json/',
          'https://ip-api.com/json/',
          'https://freegeoip.app/json/',
          'https://ipinfo.io/json'
        ];

        let response: any = null;
        let detectedCountryCode = '';

        // Try each service until we get a successful response
        for (const service of services) {
          try {
            const res = await fetch(service);
            if (res.ok) {
              const data = await res.json();
              response = data;
              
              // Normalize country code from different services
              if (service.includes('ipapi.co')) {
                detectedCountryCode = data.country_code || data.country;
              } else if (service.includes('ip-api.com')) {
                detectedCountryCode = data.countryCode;
              } else if (service.includes('freegeoip.app')) {
                detectedCountryCode = data.country_code;
              } else if (service.includes('ipinfo.io')) {
                detectedCountryCode = data.country;
              }
              
              if (detectedCountryCode) break;
            }
          } catch (serviceError) {
            console.log(`Failed to get location from ${service}:`, serviceError);
            continue;
          }
        }

        if (detectedCountryCode && response) {
          const country = countries.find(c => c.code === detectedCountryCode.toUpperCase());
          
          if (country) {
            console.log('Location detected:', country.name, country.code);
            setLocationData({
              country: country.name,
              countryCode: country.code,
              phonePrefix: country.phone,
              timezone: country.timezone,
              currency: country.currency,
              language: country.language,
              isDetected: true,
              isLoading: false,
              error: null,
            });
            return;
          }
        }

        // If IP detection fails, fall back to timezone detection
        console.log('IP detection failed, falling back to timezone detection');
        const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        
        const timezoneCountryMap: { [key: string]: string } = {
          'Asia/Jakarta': 'ID',
          'America/New_York': 'US',
          'America/Los_Angeles': 'US',
          'America/Chicago': 'US',
          'Europe/London': 'GB',
          'Australia/Sydney': 'AU',
          'Europe/Berlin': 'DE',
          'Europe/Paris': 'FR',
          'Europe/Rome': 'IT',
          'Europe/Madrid': 'ES',
          'Europe/Amsterdam': 'NL',
          'Asia/Tokyo': 'JP',
          'Asia/Seoul': 'KR',
          'Asia/Shanghai': 'CN',
          'Asia/Kolkata': 'IN',
          'Asia/Singapore': 'SG',
          'Asia/Kuala_Lumpur': 'MY',
          'Asia/Bangkok': 'TH',
          'Asia/Ho_Chi_Minh': 'VN',
          'Asia/Manila': 'PH',
          'America/Sao_Paulo': 'BR',
          'America/Mexico_City': 'MX',
          'America/Toronto': 'CA',
        };

        const fallbackCountryCode = timezoneCountryMap[timezone];
        const fallbackCountry = countries.find(c => c.code === fallbackCountryCode);
        
        if (fallbackCountry) {
          console.log('Timezone fallback detected:', fallbackCountry.name);
          setLocationData({
            country: fallbackCountry.name,
            countryCode: fallbackCountry.code,
            phonePrefix: fallbackCountry.phone,
            timezone: fallbackCountry.timezone,
            currency: fallbackCountry.currency,
            language: fallbackCountry.language,
            isDetected: true,
            isLoading: false,
            error: null,
          });
        } else {
          // Final fallback to US
          console.log('All detection failed, using US as default');
          const defaultCountry = countries.find(c => c.code === 'US')!;
          setLocationData({
            country: defaultCountry.name,
            countryCode: defaultCountry.code,
            phonePrefix: defaultCountry.phone,
            timezone: defaultCountry.timezone,
            currency: defaultCountry.currency,
            language: defaultCountry.language,
            isDetected: false,
            isLoading: false,
            error: 'Could not detect location',
          });
        }

      } catch (error) {
        console.error('Location detection error:', error);
        // Final fallback to US
        const defaultCountry = countries.find(c => c.code === 'US')!;
        setLocationData({
          country: defaultCountry.name,
          countryCode: defaultCountry.code,
          phonePrefix: defaultCountry.phone,
          timezone: defaultCountry.timezone,
          currency: defaultCountry.currency,
          language: defaultCountry.language,
          isDetected: false,
          isLoading: false,
          error: 'Location detection failed',
        });
      }
    };

    detectLocation();
  }, []);

  return locationData;
};

export { countries, timezones, currencies, languages };
